//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PisFirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lab5 : DbContext
    {
        public lab5()
            : base("name=lab5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalCategory> AnimalCategory { get; set; }
        public virtual DbSet<ApplicantCategory> ApplicantCategory { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<MunicipalDistrict> MunicipalDistrict { get; set; }
        public virtual DbSet<Omsu> Omsu { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<RegistrationCard> RegistrationCard { get; set; }
        public virtual DbSet<UrgencyType> UrgencyType { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
