//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PisFirst.Models
{
    using System;

    public partial class RegistrationCard
    {
        public int rc_id { get; set; }
        public System.DateTime rc_application_date { get; set; }
        public string rc_animal_habitat { get; set; }
        public string rc_capture_reason { get; set; }
        public System.DateTime rc_signing_date { get; set; }
        public string rc_signature { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> om_id { get; set; }
        public Nullable<int> or_id { get; set; }
        public Nullable<int> ut_id { get; set; }
        public Nullable<int> anc_id { get; set; }
        public Nullable<int> apc_id { get; set; }
        public Nullable<int> as_id { get; set; }
    
        public virtual AnimalCategory AnimalCategory { get; set; }
        public virtual ApplicantCategory ApplicantCategory { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual Omsu Omsu { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual UrgencyType UrgencyType { get; set; }
    }
}
