//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PisFirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbContext : DbContext
    {
        public TestDbContext()
            : base("name=TestDbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalCategory> AnimalCategory { get; set; }
        public virtual DbSet<ApplicantCategory> ApplicantCategory { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<MunicipalDistrict> MunicipalDistrict { get; set; }
        public virtual DbSet<Omsu> Omsu { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<RegistrationCard> RegistrationCard { get; set; }
        public virtual DbSet<UrgencyType> UrgencyType { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
